### ISSUE TITLE
Powered by Wechaty

### ISSUE THREAD

**Issue by huan** [imWildCat/wechaty-slave#1]
Could you please put a __Powered by Wechaty__ badge in README?

[![Powered by Wechaty](https://img.shields.io/badge/Powered%20By-Wechaty-green.svg)](https://github.com/wechaty/wechaty)

```markdown
[![Powered by Wechaty](https://img.shields.io/badge/Powered%20By-Wechaty-green.svg)](https://github.com/wechaty/wechaty)
```

Thanks!

**Comment by MikeChongCan** [comment]
@zixia Thanks for you reminder. It is very honoured to be powered by WeChaty!
